### ISSUE TITLE
p4 2015.1 reconcile improvements

### ISSUE THREAD

**Issue by amaiorano** [p4paul/p4-jenkins#15]
Hi Paul,

I'm sorry for using this channel to contact you, but I couldn't figure out a better way. I noticed this post from you on the Jenkins JIRA where you say "The 15.1 reconcile improvements will be much better as we store the have sync time and use that for updates.":

https://issues.jenkins-ci.org/browse/JENKINS-25341

I am using 2015.1 and have noticed that "p4 reconcile -m" seems to work despite the fact that I do NOT have modtime set, nor +m on my files. Is this the reason? I checked through the [release notes](https://www.perforce.com/perforce/doc.current/user/relnotes.txt) but could not find anything to the effect that reconcile now uses sync time with -m.

Again, I'm sorry for using this channel, but I would very much appreciate this information, and you seem the right person to ask.

Thanks!

**Comment by p4paul** [comment]
Hi Antonio,

Thanks for contacting me, I don't mind which channel you use.

The 'reconcile -m' was introduced in the 2014.1 server, but needed the modtime in the workspace set.  I added support for this in Jenkins to allow for faster cleanups.

In the 2015.1 release the server stores extra modtime information in the db.have table, so setting the modtime in the workspace is no longer required.  The release notes elude to the server storage of mod time:

	#933680 *
	    'p4 reconcile -m' will now perform digest checks on files whose
	    modtime is older (not just newer) than the modtime value stored
	    on the server.

I hope that helps answer your question.

Please bear in-mind that for old workspaces you may need to resync your files for the server to update the modtime.

Kind regards,
Paul


> On 3 Nov 2015, at 21:50, Antonio Maiorano <notifications@github.com> wrote:
> 
> Hi Paul,
> 
> I'm sorry for using this channel to contact you, but I couldn't figure out a better way. I noticed this post from you on the Jenkins JIRA where you say "The 15.1 reconcile improvements will be much better as we store the have sync time and use that for updates.":
> 
> https://issues.jenkins-ci.org/browse/JENKINS-25341
> 
> I am using 2015.1 and have noticed that "p4 reconcile -m" seems to work despite the fact that I do NOT have modtime set, nor +m on my files. Is this the reason? I checked through the release notes but could not find anything to the effect that reconcile now uses sync time with -m.
> 
> Again, I'm sorry for using this channel, but I would very much appreciate this information, and you seem the right person to ask.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub.
> 



--------------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. If 
you have received this email in error please notify the system manager. Please 
note that any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of Perforce Software. Finally, 
the recipient should check this email and any attachments for the presence of 
viruses. Perforce Software accepts no liability for any damage caused by any 
virus transmitted by this email.

Perforce Software UK Ltd is registered in England and Wales as company no. 
3816019 at the following address: West Forest Gate, Wellington Road, Wokingham,
RG40 2AT, UK
--------------------------------------------------------------------------------

**Comment by amaiorano** [comment]
Hi Paul,

If I understand correctly, what you're saying is that 2015.1 now stores the 'sync time' in the db.have table for each file you sync, so 'p4 reconcile -m' is able to compare the local time stamp against this sync time, right? This is why this feature works now without requiring modtime enabled in the workspace (or +m on files)?

I must say, if this feature now works this way, I am surprised there hasn't been more fanfare from Perforce about it. This is a HUGE time saver for those of us working with large files, like in games dev. I almost wonder why 'p4 reconcile' doesn't always use this method of timestamp checking without requiring the '-m' parameter, although I suspect it's because of the (rare) chance your locally modified file somehow has the same time stamp as the sync time in db.have, in which case the diff won't be detected.

I think it would be a good idea to update the docs about this feature, and perhaps write an article. Currently, the following doc and article that deal with this feature are out of date with the latest changes:

- [The online help doc](https://www.perforce.com/perforce/r15.1/manuals/cmdref/p4_reconcile.html) for 2015.1 doesn't say anything about _not_ requiring modtime or +m, as you described.

- [This article](https://www.perforce.com/blog/150629/making-p4-status-p4-reconcile-better-faster) from June 29 2015 states that "When working in a centralized fashion against a shared server you can simply run p4 status –m or p4 rec –m to gain these performance benefits, as long as you have set modtime in your client.". This is not accurate anymore.

Thank you again for taking the time to answer my questions! I really appreciate it.

Antonio

**Comment by p4paul** [comment]
Thanks for bringing the blog article to my attention, I'll talk to our marketing team and get that cleared up.

Yes, it is a big time save.  I have another 'p4' Jenkins user send me graphs of the time saved on his builds, some were almost cut in half.  Perhaps they might make a bigger fanfair at MERGE 2016, still it is a very neat enhancement.

**Comment by p4paul** [comment]
Situation confirmed in earlier posts, but waiting for blog article to get updated.
